### PR TITLE
Pytorch rebased

### PR DESCRIPTION
**Pull request by vlimant**
rebasing https://github.com/thongonary/mpi_opt/pull/10

the path of the input files is not correct @thongonary

### CODE REVIEW

**Comment by vlimant** [comment]
at this point 
mpirun -n 3 --tag-output python3 hyperparameter_search_option3.py --block-size 2 --verbose --example topclass  --epochs 1 --num-iterations 10 --torch --batch 2
runs, on the cpu.
enabling gpu with 

@@ -36,7 +36,7 @@ class TorchBuilderFromFunction(BuilderFromFunction):
     def builder(self, *params):
         args = dict(zip([p.name for p in self.parameters], params))
         model_pytorch = self.model_fn(**args)
-        return ModelPytorch(None, filename=model_pytorch) 
+        return ModelPytorch(None, filename=model_pytorch, gpus=1) 
 
makes it crash

**Comment by vlimant** [comment]
@vloncar there is something very fishy with enabling the GPU for torch in this branch.

**Comment by vloncar** [comment]
@vlimant The crash happens due to mismatch between cuDNN that PyTorch expects (at least version 6) vs the system one (version 5.1). I have found two ways to solve this:
1) Disable cuDNN in PyTorch, but this probably has a performance impact. Putting:
`import torch.backends.cudnn as cudnn`
`cudnn.enabled = False`
before the `model.cuda()` call in `MPITModel` disables cuDNN and the problem is gone.
2) Install newer cuDNN over the old one. But this requires reinstallation of TensorFlow. Alternatively, download cuDNN 7.0.5 and unpack `libcudnn.so` (all 3 files) somethere and run mpi_opt with
`LD_PRELOAD=/path/to/libcudnn.so mpirun...`
This will not affect the system libraries, and current TensorFlow installation will continue to work.

**Comment by vlimant** [comment]
merging to avoid to diverge again. we have a solution in sight

**Pull request merged**
